### ISSUE TITLE
Roadmap (v0.1)

### ISSUE THREAD

**Issue by ateich** [ateich/Primeflix#1]
- [ ] Display shows available for free on Amazon Prime Video
- [ ] Make shows a link to seasons of the show
- [ ] Make seasons link to episodes of the season
- [ ] Make episodes link to video player
